### ISSUE TITLE
Add a multi select on the coach for communication channels

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#109]
Accessed by a floating action button

If we added a multi select on the coach, to select what apps they use for contacting with their phone number
e.g.
* whatsapp
* signal
* telegram
* etc.

And then on the coach info page, we can have buttons that take the user to that app connecting with that person.

This is in contrast to the share buttons, which allow the user to select the app to share in using their native share options.

In the connecting with a specific person we want to enable getting into that app and messaging that specific person.

## Todo

- [x] Get selected apps.
- [x] Get coaches work phone number
- [x] create buttons to open that app with that number
