### ISSUE TITLE
Dashboard: 3-Month plan page

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#145]
Is a tickable task.
* opens the form for adding activites as an activity in a modal
* once done this task is ticked on the dashboard
* they then access it from 'my plans'

Is an independent 3 month plan page which only has the create new plans form

It should deal with the not logged in flow to get them logged in.

It should also be accessible via QR code as an individual activity (therefore could be a component)

## Todo

- [x] Build and style activity page(s)
- [x] add authorisation needed (also for html version?)
- [x] refactor Q list to web component and add API functionality to send up answers
- [x] use web component in dashboard 3 month plan management page.
- [x] link dashboard 3-month plan page to activity in modal
- [x] connect completion of 3-month plan to dashboard/user state
- [x] fix displaying of activities in list

![image](https://github.com/ZumeProject/zume-training-system/assets/9816214/f6fecdee-3fcc-4285-93d5-5c9b540a31f8)

**Comment by ChrisChasm** [comment]
https://zume5.training/en/zume_activities/3monthplan
