### ISSUE TITLE
Anonymous layer

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#158]
## Todo

- [x] Get latest designs from Chad
- [x] adjust About page to match design
- [x] #165
- [ ] #182
- [ ] #183
  - push back on this?
  - would this require 2 clicks to start the video instead of 1?
  - could we get the vimeo videos to have a thumbnail that matches the desired graphic?
- [ ] #160
- [x] #159
- [ ] #161
- [x] Add launch course button in footer
