### ISSUE TITLE
Activity Page: HTML/CSS Installed

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#197]
## Todo

- [ ] adjust titles of images and titles to be captions? or something [genmapping
- [ ] 4fields needs divs --> p tags
- [ ] 33group needs title p strong being h4
- [ ] go through and fix html, removing div tags etc.
