### ISSUE TITLE
add changing of personal language to profile page

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#23]
## Automatic catching of language

when someone changes their language on the front-end
save the new language to their profile.

## In profile page

Add multiselect for user to show what languages they speak
pre populated with their current UI language
"We think you speak French" as you are reading the site in French

## Todo

- [x] change user language cookie when language switcher is used
- [x] when user registers, add current UI language as their UI language
- [x] language fall backs
  - [x] user logged in --> use user saved language
  - [x] user not logged in --> use cookie saved language
  - [x] use the language in the url
- [x] display user language select in profile
- [x] change language to user language on login
