### ISSUE TITLE
fix: large ul bullet style is affecting spacing after first line of li text

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#238]
Notice the larger line spacing between 1st and 2nd line
Reducing the size of the bullet fixes this issue

![Image](https://github.com/ZumeProject/zume-training-system/assets/9816214/dd4efda9-7ce9-43ac-b364-8d809b2cc72f)

## Todo

- [ ] make the normal ul be normal list points with some margin inline start
- [ ] make large bullets be a special style
- [ ] Refactor usage of ul tag around site to take the above into account (or create a bullet-list class for those lists that need bullets)
