### ISSUE TITLE
Build a model magic link with a user login and redirect to user magic link.

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#43]
I think we need a standard example of a magic link that begins with a user login root and then redirects to a user magic link. We could add this to the starter plugin, we should show and tell this at the DT summit, and we need it for a handful of Zume micro apps we're going to make. 

Example:
/zume_app/user_app -> if not logged in, login screen with SSO -> success login, redirect to appropriate user magic link

No, imagine the magic link has a raw root/type/ page that hosts it own login module without redirect, and once successful, it looks up and redirects to the magic link for that user.

It would be a model that could be reused for any number of login required magic link apps.

Here's a use case. Curtis want to register a ton of his contacts in bulk, make them zume trainees and auto connect himself as the coach. Ideally, he would have a single link that he would distribute in his email list to thousand s of people, they follow that link and screen one -> they register, screen two -> they fill out their full profile , screen three -> get get a confirmation that they have been connected with Curtis as a coach.

## Todo

- [x] create a clone of the magic link user app
- [x] if not logged in redirect to login page with redirect_to back to the magic link
- [x] if user logged in show them the app and use the logged in user info and app owner info as needed by the app
- [x] add a switch to login templates to remove header on certain query param
