### ISSUE TITLE
Build out utility pages

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#58]
nav and footer are locked

resources page is gone

## footer

* get a coach --> clarifying page on what getting a coach is --> register and get a coach wizard.
  * wizard --> fill out phone, name and location --> how can we serve you question --> connected
  * (could in the future have a magic link that allows users within a group to get a coach from within their group)
* mobile page --> put links in their own places

## Todo

- [x] nav bar
- [x] footer
- [x] Get a coach
- [x] how to follow Jesus
- [x] guidebook
  - [x] if a user is logged in hide the register and bottom paragraph
- [x] Mobile app
- [x] donate --> external link
- [x] fix sticky nav to come all the way down the page
