### ISSUE TITLE
connect guidebook page to downloadable resources

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#65]
These resources don't exist yet.

Someone will need to create the pdfs for these from the course content

The pdf delivery will probably use the same structure as the zume download but with extra information.

## Todo
 
- [ ] Create new zume resources post type similar to zume downloads post type
- [ ] add image, title, short text with download link for each resource
- [ ] If a user is not logged in grab first 4-6 resources
- [ ] if a user is not logged in download button opens modal to register to access (and go through which wizard???)
- [ ] If a user is logged in show all zume resources
