### ISSUE TITLE
fix SSO login + email change

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#73]
If a user is allowed to change their email address if they signed up with SSO, then things get crazy.

* user signs up with google sso email foobar@gmail.com
* user changes their email address to foobarday@gmail.com
* logs out and back in with foobar@gmail.com SSO
* this creates a new user as currently the registration system is looking for the email address user, not for which account is linked to that SSO...

maybe it should check whether a user already has that SSO account linked and login as that user.

In which case you might want to also allow them to unlink their SSO account from their email address 

## TODO

- [ ] Also check if a user account is linked to this SSO account, and log in as that user.
- [ ] or disallow changing email address on an account that has only signed up with SSO

**Comment by squigglybob** [comment]
It would be ideal to seperate
authentication email
and
communication email

- [ ] prepopulate the user_email with the user auth email, but then cut off the babysitting that updates it.
- [ ] change the profile to update user_email but not the user auth email
- [ ] clarify that the profile info is for communication
- [ ] add another section underneath for managing user login
